apiVersion: batch/v1
kind: Job
metadata:
  name: load-tester
spec:
  completions: 3
  parallelism: 1
  template:
    metadata:
      name: load-tester
    spec:
      containers:
      - name: load-test
        image: jdowni000/load-test:v1
        command: ["bash", "-c", "ab -c 10 -n 100000 http://nginx-load-test/"]
      restartPolicy: Never
