apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-load-test
  labels:
    app: nginx
    use: load-test
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
      use: load-test
  template:
    metadata:
      labels:
        app: nginx
        use: load-test
    spec:
      containers:
      - name: nginx-load-test
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-load-test
spec:
  selector:
    app: nginx
    use: load-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
